apiVersion: v1
kind: PersistentVolume
metadata:
  name: application-logs
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100M
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
