apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: application-logs
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 100M
